### ISSUE TITLE
Bitmap.getWidth() on null object Refference

### ISSUE THREAD

**Issue by feriyalsusanto** [bamlab/react-native-image-resizer#53] opened 2016-10-18 08:06 UTC
Hi, 

I got this error when createResizedImage
![screenshot_20161018-150447 1](https://cloud.githubusercontent.com/assets/10955932/19469169/57353824-9544-11e6-80c4-42eed8cd14f5.png)

and my code:
`ImageResizer.createResizedImage(source.uri, 800, 600, 'JPEG', 80) {....}`
where source.uri is from ImagePicker.

Thanks

**Comment by Monte9** [comment] 2016-10-22 02:34
I am running into the same issue.

**Comment by mafelix** [comment] 2016-10-25 21:38
I'm getting the problem too, but I assume your source.uri is wrong as well as mine. 
Will test if it's null, because I'm inputing a base64 string as the image.

**Comment by leoabacade** [comment] 2016-10-27 05:03
same here, some time image resize successfully, so not sure what went wrong

![14795880_10154135086158163_1757021924_o png](https://cloud.githubusercontent.com/assets/2664504/19755091/a6774f6e-9c45-11e6-9155-d77cfbc3cbdb.jpeg)

**Comment by dyguests** [comment] 2016-11-01 04:02
I got same issue.It's work on iOS,but not work on Android.
![2016-11-01 12 01 28](https://cloud.githubusercontent.com/assets/7933189/19879165/f203ac64-a02a-11e6-9e2b-c1ebe4f52812.png)

**Comment by dyguests** [comment] 2016-11-03 07:07
It seems happened on `Bitmap scaledImage = ImageResizer.resizeImage(sourceImage, newWidth, newHeight);` return null,and then call `rotatedImage = ImageResizer.rotateImage(scaledImage, rotation);`

I think it happens when imagePath is a url,not a file path(`sourceImage = BitmapFactory.decodeFile(imagePath, options);` )

maybe..?!?

**Comment by 4ian** [comment] 2016-11-03 23:18
Hey guys, thanks for reporting this issue! It would be awesome if you could make a sample project (use this one: https://github.com/bamlab/react-native-image-resizer/tree/master/example) and tell what to do next (for example: run `react-native run-android`, click there and boom!) to reproduce the bug. It would speed up the bug hunt a lot for me!
I'll be happy to fix the issue then! :D 

cc @dyguests @leoabacade @Monte9 @mafelix @feriyalsusanto

**Comment by dyguests** [comment] 2016-11-04 02:50
@4ian 
Aleady fixed.The newest code can resize a base64 uri,

```java
ImageResizer.loadBitmapFromBase64(imagePath);
```

But the published lib on npm("react-native-image-resizer": "0.0.11") can not resize a base64 uri.

Waiting for the new publish version.
Thanks.....
:)

**Comment by 4ian** [comment] 2016-11-05 21:33
Oops I totally forgot that latest changes were not published on npm. That's fixed with version 0.0.12 :)
I'll close the issue if someone can confirm that it's working with this new version.

**Comment by Nodonisko** [comment] 2019-02-01 10:32
Not tested with base64, but still happening for URIs on some devices

**Closed** 2022-09-09 03:03 UTC
Labels: wontfix
