### ISSUE TITLE
duplicate entry: android/support/v7/appcompat/R$anim.class

### ISSUE THREAD

**Issue by sadhwaniyash6** [bamlab/react-native-image-resizer#15] opened 2016-06-16 18:46 UTC
dependencies {
    compile project(':react-native-image-resizer')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-android-permissions')
        compile fileTree(dir: "libs", include: ["*.jar"])
        compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
The above are my dependencies in build.gradle in android\app\

and on running I get this error:

:app:packageAllDebugClassesForMultiDex FAILED
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: android/support/v7/appcompat/R$anim.class
Information:BUILD FAILED

I needed some help resolving this.

**Comment by sadhwaniyash6** [comment] 2016-06-16 19:15
![capture](https://cloud.githubusercontent.com/assets/11190073/16129969/c0b14f1c-3424-11e6-9b2d-123691c1dd46.PNG)

**Comment by sadhwaniyash6** [comment] 2016-06-16 19:16
I get the above error on a fresh "react-native init sampleApp" and just following the instructions mentioned in the Readme of this library

**Comment by dcworldwide** [comment] 2016-06-18 03:27
I'm having the same issue compiling for Android. @sadhwaniyash6 Did you find a solution? 

> :app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug UP-TO-DATE
:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

> 
> :app:dexDebug FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:dexDebug'.
> > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by dcworldwide** [comment] 2016-06-18 04:07
@sadhwaniyash6 The issue is actually fixed in master. Try installing the latest directly via git instead of using version 0.0.4. 


> "react-native-image-resizer": "git+https://github.com/bamlab/react-native-image-resizer.git"`

**Comment by Almouro** [comment] 2016-06-27 18:39
Thanks @dcworldwide !!
@4ian should we release a new version?

**Comment by 4ian** [comment] 2016-06-27 18:52
@Almouro Can do it if you wish, but when looking at the diff, it's quite strange that the issue is fixed by using master: https://github.com/bamlab/react-native-image-resizer/compare/v0.0.4...master
Only change is the deployment target for iOS ^^

**Comment by 4ian** [comment] 2016-06-27 19:15
I've nevertheless released a new version, even if it's not fixing that. :)

**Comment by stoffern** [comment] 2016-07-05 14:19
The `app:dexDebug` error does not hav anything to do with this project.
This error can appear for native plugins in react native when there are inconsistency in the node_modules and Android dex cache.

Best way to fix this is: 
```
- remove node_modules
- npm clean cache
- npm i
- start project in Android Stuido and run "Rebuild Project" under "Build"

```

**Comment by 4ian** [comment] 2016-07-05 23:09
I'm closing this issue as it's not related to this module :)

**Closed by 4ian** 2016-07-05 23:09 UTC

**Comment by sibelius** [comment] 2016-07-17 17:03
@stoffern the right command is `npm cache clean` instead of `npm clean cache`

**Comment by stoffern** [comment] 2016-07-17 17:40
@sibelius tnx for the feedback, comment updated
