### ISSUE TITLE
NOT WORKING WITH SHARE EXTENSIONS 

### ISSUE THREAD

**Issue by OmarBasem** [bamlab/react-native-image-resizer#190] opened 2019-08-10 07:31 UTC
This library does not work with share extensions on ios. The native code reaches this line: (line 137 in RCTImageResizer.m) ` [_bridge.imageLoader loadImageWithURLRequest:[RCTConvert NSURLRequest:path] callback:^(NSError *error, UIImage *image)` and then something goes wrong and it does not work.

**Comment by Lichwa** [comment] 2019-11-14 08:58
https://github.com/facebook/react-native/issues/26014

**Comment by PierreCapo** [comment] 2019-11-14 09:12
@Lichwa Is this still occurring with the last version `1.1.0` of react-native-image-resizer ?

**Comment by Lichwa** [comment] 2019-11-14 10:53
Yes, it is. I've created my fork that is resizing image before loading it into memory and I no longer had problem with share extension exceeding memory limit.

https://github.com/bamlab/react-native-image-resizer/compare/master...Lichwa:master

**Comment by eladni101** [comment] 2020-01-29 11:59
@Lichwa  Hi, can you share the code of the resize in ios for a share extension?  I have the same problem :)

**Comment by idan666** [comment] 2020-01-29 12:35
+1 need to know how this can work in share extension!!!!!!! @eladni101 ! @Lichwa

**Comment by robertbarclay** [comment] 2020-08-06 14:12
created a PR to fix this issue. I was having the same problem and found it to be a memory issue caused by trying to load the full image into a bitmap that is just going to be resized, so changed it preemptively load it the size we want it loaded. https://github.com/bamlab/react-native-image-resizer/pull/248

**Comment by PierreCapo** [comment] 2020-08-09 11:19
Closing this issue because the fix has just been merged and deployed. Feel free to reopen it if you encounter the problem again.

**Closed by PierreCapo** 2020-08-09 11:19 UTC
